### ISSUE TITLE
Download Now link is not working for SfB Server 2019 GA

### ISSUE THREAD

**Issue by bament-hun** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1144]
Hello Team,
I've just noticed that cannot find anywhere to download the SfB Server 2019 GA and the Download Now hyperlink is not working anymore
https://go.microsoft.com/fwlink/?linkid=2005336 - attached link is not working

please fix
Thanks,

**Comment by jambirk** [comment]
@bament-hun That link was put in for the pre-release installations, and now that we've released the target of that link has been removed. We'll remove the link from the page. Going forward, you'd need to go through commercial purchase channels to get the server installers.

**Comment by bament-hun** [comment]
Thanks for your response. As the orinial request was coming from a customer, are we able to direct the customers to the proper page, where they can make the commercial purchase? Might be this is still not clear for everybody.

**Comment by AndreaBarr** [comment]
@jambirk Thoughts on this last comment?

**Comment by jambirk** [comment]
The link has been put back in place, but is still broken. The PG is working internally on either placing a version of Server 2019 on the Evaluation center or better messaging the download process on the VLSC site. This will take some time to sort out, but is getting attention.

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this issue? Thanks!

**Comment by jambirk** [comment]
I know it's underway. @LanaChin is assigned to update when this becomes available. I do see the link is there, but it currently points to download center rather than the eval center.

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@LanaChin Hi Lana, any updates on this issue?

**Comment by scanum** [comment]
@LanaChin Hi Lana, any updates on this issue?

**Comment by tonysmit** [comment]
@jambirk - Can you follow up on this please so we can get it resolved? It's been open for quite a while. Thanks!

**Comment by jambirk** [comment]
just confirmed link to eval center from the SfB Server splash page (https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-server-2019) is working. also updated that fwlink and dropped it in the page in place of the direct eval center link. Closing this issue. Please reopen if there are other related problems.

**Comment by scanum** [comment]
@bament-hun Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
