### ISSUE TITLE
Team Discovery is not showing anymore in the UI of Teams app

### ISSUE THREAD

**Issue by omarmallat** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3785]
if I follow this page, I get nothing to work. First, the "Team discovery" option is not available in the Teams Settings in the UI. additionally, if I run the mentioned PowerShell command, it succeeds, but still the private team is not showing while discovering teams, even if I search a specific team by name. You should consider updating this page, or clarify any special conditions that make this page irrelevant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams#feedback)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@omarmallat Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by olasandness** [comment]
This is still in "rolling out" phase, hence not available yet. Coming in second quarter of 2020 it seems. According to the roadmap: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=discovery%2Cof%2Cprivate%2Cteams

**Comment by docbt** [comment]
Rollout phase? The missing search filed in the Teams UI is a new issue. It was there in the past!

If I run the "Set-Team" command, it fails with:
`Set-Team : Error occurred while executing
Code: BadGateway
Message: Failed to execute backend request.`

**Comment by olasandness** [comment]
Ok, @docbt, probably I misunderstood. I'm trying to get the "discovery of private teams" to work as well - both from the UI and using Graph/Flow. In my contact with Microsoft support, I got this:

> _I was reviewing this case and found out that the feature that you are looking is in currently rolling out and will be globally available by Q2 CY2020, you can also confirm the same from here as well - https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Microsoft%20Teams%2CRolling%20out_

**Comment by scanum** [comment]
@omarmallat Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by karatedog** [comment]
The "Team Discovery" menu is not available for me.

**Comment by karatedog** [comment]
"This team is searchable and discoverable." also missing, when creating new teams.

**Comment by mariabarsema** [comment]
Just like everyone else, I'm wondering why this feature is not available. As we are all now jumping in Teams due to COVID-19, it is maddening not knowing if a Team already exists. We have already had several instances of people creating new Teams unnecessarily because they were not Discoverable.

**Comment by omarmallat** [comment]
I believe this issue should remain open until it is really solved. it is still not showing. and recently, they updated the admin page of Team, so when you create a private team, it will tell you CLEARLY that it will not show in the search!!! any changes in the roadmap?
<img width="199" alt="PrivateTeam" src="https://user-images.githubusercontent.com/8017412/83641934-41d47280-a5bf-11ea-9380-fa819384c090.png">

**Comment by web265p3** [comment]
For us the option is also not available. This is a shame due to the fact that we already have March 2020 now...
