### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by tsrob50** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#604]
the link to http://download.microsoft.com/download/9/0/D/90D4826A-9FD2-47D2-B911-97BF1737F4F7/SkypeRoomSystems_v2.omsview seems to be broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7ceb43-d37f-8918-855e-ac8375875e6e
* Version Independent ID: 1b48ad59-2737-7ac4-8ad5-80904c0e3ccc
* Content: [Deploy Skype Room Systems v2 management with OMS](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-oms)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/with-oms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/with-oms.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
I've tracked down the issue, the target file was misnamed in the course of an update recently. It should be fixed very soon.

**Comment by kenwith** [comment]
@jambirk - thank you!

**Comment by jambirk** [comment]
The change on DLC was just implemented a few minutes ago, please try now.

**Comment by tsrob50** [comment]
Now it's working.  Thanks!

**Comment by dmoore4** [comment]
The link published here is still broken:  https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/with-oms#create-a-skype-room-systems-v2-dashboard-by-using-the-import-method

**Comment by dmoore4** [comment]
Thanks @jambirk It was failing for me in Chrome on a Mac.  I opened Safari and it works there.  TY
