### ISSUE TITLE
Re-open the feedback about non-working auto launch or disable auto launch instructions until the issue is fixed

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#826]
The situation is now confusing for people who look this page first time: There is information how to disable auto launch. Unfortunately, the switch is not working & confirmed by Microsoft. However, the feedback that contains the information about non-working noAutoStart parameter is closed. Closed feedback issues are more difficult to find from the doc page.

Please either:
- Re-open the feedback about Disable autolaunch not working or remove the instructions how to disable auto launch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b13006b-d1de-8bc7-e0c6-b7022af0e731
* Version Independent ID: d29dae65-bb28-8767-cfd7-07d2ed5fd460
* Content: [Install Microsoft Teams using MSI](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by BinneyJ** [comment]
msiexec /i Teams_windows.msi OPTIONS="noAutoStart=true"
Seems like noAutoStart=False would mean that it will autostart

**Comment by PanuSaukko** [comment]
Even if you set: msiexec /i Teams_windows.msi OPTIONS="noAutoStart=true", Teams will start automatically.

**Comment by AndreaBarr** [comment]
@PanuSaukko Thank you for this feedback

I agree this parameter should be fixed or the document updated. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by Ath3na** [comment]
Why are these closed, shouldn't they be left open until the reported issue is fixed? Please fix this installer so the command works so we can disable autostart of the application

**Comment by AndreaBarr** [comment]
@Richklv426 Thank you for this feedback

We just yesterday updated our always evolving process to keep these issues open. We have the issue logged into to backlog so that we can get this installer issue addressed. We apricate you helping to make the docs better.

**Comment by Florin-Anghel** [comment]
The switch indeed is not working and the fact that the folder itself shows up in the user profile after teams is launched, gives little control for post-configurations.
For example, modifying the <"openAtLogin":true> in false in the desktop-config.json file is not possible since the folder does not exist immediatly after install. A script using active setup is not a suitable solution either since it would require the user to have launched Teams before logging off.

**Comment by PBrawn** [comment]
This is probably one of the most abysmally implemented bits of software MS have ever created, with the exception of windows ME.
I really feel MS needs to take the app out of service and go back to the drawing board. This is nothing but a hindrance in an educational environment for us IT admins. I've had complaints for the past 2 months about it now, and MS have still failed to find a resolution for something as simple as disabling run at startup!
The above "Clean up and redeployment procedure" is a joke too. Who really thought that on multi-user computers, in a school, us admins would find the time to run a cleanup script aimed at each user?

**Comment by oclaros** [comment]
We have the same issue via intune. Adding /q OPTIONS="noAutoStart=false" or /q OPTIONS="noAutoStart=true" sill results in 'auto-start'. This is quit annoying for the end-user. Still trying to figure out how to deploy via Intune for Education.

**Comment by nsshommo** [comment]
> @nsshommo could you please investigate this issue?

Okay, I am looking at this issue.

**Comment by scanum** [comment]
@nsshommo Following up on this issue. Any updates?

**Comment by nsshommo** [comment]
Nothing yet.

**Comment by scanum** [comment]
@nsshommo Following up on this issue. Any updates?

**Comment by PBrawn** [comment]
I learned that this MSI switch is only for preventing it from auto-starting after installation. It has nothing to do with the installed programs startup behaviour! I don't think MS have a clue about what they're doing with this. Their support seems uncommitted and feedback regarding these issues are either nonexistent or outright dismissive (i.e. closing feature request or threads like the above).

For those who want to prevent it running at startup in an enterprise environment, you can add the following GPOs. Please note that both do need to be entered if you have deployed the MSI, otherwise the installer will keep re-running and adding the user key back, or appdata's Teams.exe will run:

User registry preference:
Action: DELETE
Hive: HKEY_CURRENT_USER
Key path: Software\Microsoft\Windows\CurrentVersion\Run
Value name: com.squirrel.Teams.Teams

Computer registry preference:
Action: DELETE
Hive: HKEY_LOCAL_MACHINE
Key path: SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run
Value name: TeamsMachineInstaller

Once these keys are gone, teams will only run on request.

Hope that's of help whilst we wait for MS to sort their act out!

**Comment by scanum** [comment]
@PanuSaukko - thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
